---
strategy: polling
no_screen_padding: 'no'
dark_mode: 'no'
static_data: ''
polling_verb: get
framework_version: latest
serverless_language: ''
polling_url: "https://api.football-data.org/v4/competitions/WC/standings\r\nhttps://api.football-data.org/v4/competitions/WC/matches?dateFrom={{ \"now\" | date: \"%Y-%m-%d\" }}&dateTo={{ \"now\" | date: \"%s\" | plus: 423000 | date: \"%Y-%m-%d\" }}\r\nhttps://api.football-data.org/v4/competitions/WC/scorers"
polling_headers: X-Auth-Token={{ trmnl.plugin_settings.custom_fields_values.api_token }}&content-type=application/json
polling_body: ''
id: 327669
custom_fields:
- keyname: my_team
  field_type: select
  options:
  - Algeria: ALG
  - Argentina: ARG
  - Australia: AUS
  - Austria: AUT
  - Belgium: BEL
  - Bosnia and Herzegovina: BIH
  - Brazil: BRA
  - Canada: CAN
  - Cape Verde: CPV
  - Colombia: COL
  - Croatia: CRO
  - Curaçao: CUW
  - Czechia: CZE
  - DR Congo: COD
  - Ecuador: ECU
  - Egypt: EGY
  - England: ENG
  - France: FRA
  - Germany: GER
  - Ghana: GHA
  - Haiti: HAI
  - Iran: IRN
  - Iraq: IRQ
  - Ivory Coast: CIV
  - Japan: JPN
  - Jordan: JOR
  - Mexico: MEX
  - Morocco: MAR
  - Netherlands: NED
  - New Zealand: NZL
  - Norway: NOR
  - Panama: PAN
  - Paraguay: PAR
  - Portugal: POR
  - Qatar: QAT
  - Saudi Arabia: KSA
  - Scotland: SCO
  - Senegal: SEN
  - South Africa: RSA
  - South Korea: KOR
  - Spain: ESP
  - Sweden: SWE
  - Switzerland: SUI
  - Tunisia: TUN
  - Türkiye: TUR
  - Uruguay: URU
  - United States: USA
  - Uzbekistan: UZB
  name: Favorite team
  description: Your favorite team
- keyname: api_token
  field_type: string
  name: API Token
  description: football-data.org API Token
  placeholder: football_data_api_token
- keyname: about
  name: About This Plugin
  category: sports,news
  field_type: author_bio
  description: Display group standings and upcoming matches of your favorite national team at the Fifa World Cup 2026.<br>To access the api of <a href="https://www.football-data.org">www.football-data.org</a> you will need an account and an api-token. The world cup data is included in the free tier.
  email_address: trmnl_support@zeugs.ch
name: Fifa World Cup 2026 - Team Tracker
refresh_interval: 10
